export const categories = [
    { name: 'Art & Culture', image: require('../assets/art_culture_event.jpg') },
    { name: 'Business', image: require('../assets/business_event.jpg') },
    { name: 'Charity', image: require('../assets/charity_event.jpg') },
    { name: 'Sport', image: require('../assets/sport_event.jpg') },
    { name: 'Music', image: require('../assets/music_event.jpg')},
    { name: 'Anime', image: require('../assets/anime_event.jpg')},
    { name: 'Tech', image: require('../assets/tech_event.jpg')},
    { name: 'Food & Drink', image: require('../assets/food_drink_event.jpg')},
    { name: 'Health & Wellness', image: require('../assets/health_wellness_event.jpg')},
    { name: 'Gaming' , image: require('../assets/gaming_event.jpg')},
    { name: 'Film & Media', image: require('../assets/film_media_event.jpg')},
    { name: 'Fashion', image: require('../assets/fashion_event.jpg')},
    { name: 'Dance', image: require('../assets/dance_event.jpg')},
  ];